apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-pulse-canary
  labels:
    app: color-pulse
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-pulse
      version: v2
  template:
    metadata:
      labels:
        app: color-pulse
        version: v2
    spec:
      containers:
      - name: color-pulse
        image: swarajwadkar/color-pulse-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80

