apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-pulse-stable
  labels:
    app: color-pulse
    version: v1
spec:
  replicas: 9
  selector:
    matchLabels:
      app: color-pulse
      version: v1
  template:
    metadata:
      labels:
        app: color-pulse
        version: v1
    spec:
      containers:
      - name: color-pulse
        image: swarajwadkar/color-pulse-app:v1
        ports:
        - containerPort: 80

